spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/algamoney_api?createDatabaseIfNotExist=true&useSSL=false
    username: root
  jackson:
    date-format: yyyy-MM-dd
    default-property-inclusion: NON_NULL
    deserialization:
      fail-on-unknown-properties: true
  jpa:
    database: MYSQL
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
